import Head from "next/head";
import styled from "styled-components";
import { TopNav } from "../../components/TopNav";
import { FooterComponent } from "../../components/Footer";
import { FaEthereum } from "react-icons/fa";
import { FetchAssetFromOpenSea } from "../../functions/FetchAsset";
import { useRouter } from "next/router";

import {
  PageWrapper,
  AlignPage,
  MaxContentGrid,
} from "../../components/defaults";
import { Spacer } from "../../components/Spacer";

const Title = styled.div`
  display: flex;
  padding-top: 25%;
  height: 100%;
  max-width: 980px;
  font-family: Jet;
  font-style: normal;
  font-weight: normal;
  font-size: 24px;
  line-height: 36px;
  color: #000000;
`;

const Image = styled.img`
  height: 100%;
  max-height: 650px;
  max-width: 100%;
  margin: 10%;
`;

const Content = styled.div`
  width: 100%;
  max-width: 980px;
`;

const ArtName = styled.div`
  font-family: Jet;
  font-style: normal;
  font-weight: 900;
  font-size: 36px;
  line-height: 48px;
  text-align: right;
  color: #000000;
`;

const ArtDescription = styled.div`
  font-family: Jet;
  font-weight: 500;
  font-size: 14px;
  line-height: 18px;
  text-align: right;
  color: #000000;
`;

const OwnerCreator = styled.div`
  max-width: 450px;
  height: 100%;
  background: #f8f9fa;
  border-radius: 10px;
  padding: 15px;
  font-family: Jet;
  font-weight: 500;
  font-size: 12px;
  line-height: 18px;
  color: #000000;
  margin-bottom: 20px;
  :hover {
    cursor: pointer;
    background-color: #20ffd710;
  }
`;

const Card = styled.div`
  width: 100%;
  max-width: 470px;
  height: 100%;
  min-height: 50px;
  background: #f8f9fa;
  border-radius: 20px;
  padding: 20px;
  margin-bottom: 20px;
`;

const CardRow = styled.div`
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  width: 100%;
`;

const CardColumn = styled.div`
  display: flex;
  flex-direction: column;
  align-content: flex-start;
  width: 100%;
`;

const CardImg = styled.img`
  width: 70px;
  margin-right: 8px;
`;

const CardHeader = styled.div`
  font-family: Giaza;
  font-weight: 500;
  font-size: 24px;
  line-height: 24px;
`;

const CardDescription = styled.div`
  font-family: Jet;
  font-weight: 500;
  font-size: 14px;
  line-height: 18px;
`;

const CardStats = styled.div`
  font-family: Jet;
  font-weight: 500;
  font-size: 14px;
  line-height: 18px;
`;

export default function Page({ data, address, token }) {
  if (!data) {
    return (
      <>
        <PageWrapper>
          <AlignPage>
            <Head>
              <title>Clekta</title>
              <meta name="description" content="An Art Gallery" />
              <link rel="icon" href="/favicon.ico" />
              <meta property="og:title" content={`Your Digital Art Gallery`} />
              <meta
                property="og:description"
                content={`An online oasis of your digital art.`}
              />
              <meta property="og:url" content="https://clekta.io" />
              <meta
                property="og:image"
                content="https://clekta.vercel.app/content/home.png"
              />
              <meta property="og:image:type" content="image/jpeg" />
              <meta property="og:image:width" content="200" />
              <meta property="og:image:height" content="200" />
              <meta
                property="og:site_name"
                content={`Clekta | Your Digital Art Gallery`}
              />
              <meta name="twitter:card" content="summary" />
              <meta name="twitter:site" content="@clekta" />
              <meta name="twitter:creator" content="@clekta" />
            </Head>
            <TopNav />
            <Title>404 | We could not find any data on the token.</Title>
          </AlignPage>
        </PageWrapper>
        <FooterComponent />
      </>
    );
  }
  const router = useRouter();

  const sendToGallery = async (address) => {
    router.push(`/gallery/${address}`);
  };

  const salePrice = data?.last_sale?.total_price / Math.pow(10, 18);

  return (
    <>
      <PageWrapper>
        <AlignPage>
          <Head>
            <title>Clekta Asset | {data.name}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <title>Clekta</title>
            <meta name="description" content="An Art Gallery" />
            <link rel="icon" href="/favicon.ico" />
            <meta property="og:title" content={`Your Digital Art Gallery`} />
            <meta
              property="og:description"
              content={`An online oasis of your digital art.`}
            />
            <meta property="og:url" content="https://clekta.io" />
            <meta property="og:image" content={`${data.image_url}`} />
            <meta property="og:image:type" content="image/jpeg" />
            <meta property="og:image:width" content="200" />
            <meta property="og:image:height" content="200" />
            <meta property="og:site_name" content={`Clekta | ${data.name}`} />
            <meta name="twitter:card" content="summary" />
            <meta name="twitter:site" content="@clekta" />
            <meta name="twitter:creator" content="@clekta" />
          </Head>
          <TopNav />
          <Spacer spacer="60px" />
          <Image src={data.image_url} />
          <Content>
            <ArtName>{data.name}</ArtName>
            <ArtDescription>{data.description}</ArtDescription>
          </Content>
          <Spacer spacer="100px" />

          <MaxContentGrid>
            <OwnerCreator onClick={() => sendToGallery(data.owner.address)}>
              Owner: {data.owner.address}
            </OwnerCreator>
            <OwnerCreator onClick={() => sendToGallery(data.creator.address)}>
              Creator: {data.creator.address}
            </OwnerCreator>
          </MaxContentGrid>
          <MaxContentGrid>
            <Card>
              <CardRow>
                {data.asset_contract.image_url ? (
                  <CardImg src={data.asset_contract.image_url} />
                ) : null}
                <CardColumn>
                  <CardHeader>{data.asset_contract.name}</CardHeader>
                  <CardDescription>
                    {data.asset_contract.description}
                  </CardDescription>
                </CardColumn>
              </CardRow>
            </Card>
            <Card>
              <CardHeader>Stats & Info</CardHeader>
              <CardStats>Total Sales: {data.num_sales}</CardStats>
              {data.num_sales > 0 ? (
                <>
                  <CardStats>
                    Last Sale Price: <FaEthereum size="10" />
                    {salePrice}
                  </CardStats>
                  <CardStats>
                    Last Sale Date: {data.last_sale?.event_timestamp}
                  </CardStats>
                  <CardStats>
                    Todays Value: $
                    {(
                      data.last_sale?.payment_token.usd_price * salePrice
                    ).toFixed(2)}
                  </CardStats>
                </>
              ) : null}
            </Card>
          </MaxContentGrid>
        </AlignPage>
      </PageWrapper>
      <FooterComponent />
    </>
  );
}

// This gets called on every request
export async function getServerSideProps(context) {
  let address = context.query.asset;

  switch (address.toLowerCase()) {
    case "cryptokitties":
      address = "0x06012c8cf97bead5deae237070f9587f8e7a266d";
    default:
      break;
  }

  const token = context.query.token;

  try {
    const data = await FetchAssetFromOpenSea(address, token);
    // Pass data to the page via props

    return { props: { data, address, token } };
  } catch (error) {
    console.log(error);
    return { props: { data: null, address, token } };
  }
}
