import { useState } from "react";
import Head from "next/head";
import styled from "styled-components";
import { useRouter } from "next/router";
import { TopNav } from "../components/TopNav";
import { FooterComponent } from "../components/Footer";
import { InputComponent } from "../components/SearchBar";
import { ButtonComponent } from "../components/Button";
import { RotatedHeading } from "../components/HeadingRotatedText";
import { RecentSearchComponent } from "../components/RecentSearchItem";
import { Spacer } from "../components/Spacer";
import {
  PageWrapper,
  ContentGrid,
  Row,
  AlignPage,
} from "../components/defaults";

import { isAddress } from "../functions/AddressValidate";

const Landing = styled.div`
  width: 100%;
  height: 375px;
  border-radius: 20px;
  position: relative;
  text-align: center;
  color: black;
`;

const LandingImg = styled.img`
  width: 100%;
  height: 375px;
  border-radius: 20px;
`;

const LandingText = styled.div`
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-family: Jet;
  font-style: normal;
  font-weight: normal;
  font-size: 30px;
`;

export default function Home(): JSX.Element {
  const [ethAddress, setEthAddress]: [
    string | undefined,
    (host: string) => string | void
  ] = useState("");

  const onEthAddressHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEthAddress(event.target.value);
  };

  const router = useRouter();

  const sendToGallery = async () => {
    if (isAddress(ethAddress)) {
      router.push(`/gallery/${ethAddress}`);
    } else console.log("Not valid address");
  };

  return (
    <>
      <PageWrapper>
        <Head>
          <title>Clekta</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AlignPage>
          <TopNav />
          <Spacer spacer={"100px"} />
          <Landing>
            <LandingImg src={"/content/home.png"} />
            <LandingText>Your NFT Gallery</LandingText>
          </Landing>
          <Spacer spacer={"45px"} />
          <InputComponent
            onChange={onEthAddressHandler}
            value={ethAddress}
            placeholder={"Address / Contract"}
          />
          <ButtonComponent onClick={() => sendToGallery()}>
            Gallery
          </ButtonComponent>
          <Spacer spacer={"100px"} />
          <Row>
            <RotatedHeading>Recent Searches</RotatedHeading>
            <ContentGrid>
              <RecentSearchComponent>
                0x88207b431510DbE0AddBDaE3bD53013813fC8c71
              </RecentSearchComponent>
              <RecentSearchComponent>
                0x38eae11284842ad78Ad87AaC894c70D180A8DD38
              </RecentSearchComponent>
              <RecentSearchComponent>
                0x223716c5aa5fd892c0daff1f24d4531272e8b12d
              </RecentSearchComponent>
              <RecentSearchComponent>
                0x38eae11284842ad78Ad87AaC894c70D180A8DD38
              </RecentSearchComponent>
              <RecentSearchComponent>
                0x38eae11284842ad78Ad87AaC894c70D180A8DD38
              </RecentSearchComponent>
              <RecentSearchComponent>
                0x38eae11284842ad78Ad87AaC894c70D180A8DD38
              </RecentSearchComponent>
            </ContentGrid>
          </Row>
          <Spacer spacer={"100px"} />
        </AlignPage>
      </PageWrapper>
      <FooterComponent />
    </>
  );
}
