import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

//////
import { useState } from "react";
import { InputComponent } from "../components/SearchBar";
import { TitleComponent } from "../components/Title";
import { ButtonComponent } from "../components/Button";
import { RotatedHeading } from "../components/HeadingRotatedText";
import { RecentSearchComponent } from "../components/RecentSearchItem";
import { Spacer } from "../components/Spacer";

import { NFTComponent } from "../components/NFT";

export const RowWrapper = styled.div`
  display: flex;
  flex-direction: row;
  width: 980px;
`;

const ContentGrid = styled.div`
  display: flex;
  width: 100%;
  flex-wrap: wrap;
  align-items: flex-start;
  justify-content: space-around;
  max-width: 980px;
`;

export default function Home(): JSX.Element {
  const [ethAddress, setEthAddress]: [
    string | undefined,
    (host: string) => string | void
  ] = useState("");

  const onEthAddressHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEthAddress(event.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Clekta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NFTComponent
        name={"Founder Cat #3"}
        family={"CryptoKitties"}
        isFeatured={true}
        img={
          "https://img.cryptokitties.co/0x06012c8cf97bead5deae237070f9587f8e7a266d/1971632.svg"
        }
      />

      <TitleComponent>Clekta</TitleComponent>
      <InputComponent
        onChange={onEthAddressHandler}
        value={ethAddress}
        placeholder="0x"
      />
      <ButtonComponent>Gallery</ButtonComponent>
      <Spacer spacer={"100px"} />
      <RowWrapper>
        <RotatedHeading>Recent Searches</RotatedHeading>
        <ContentGrid>
          <RecentSearchComponent>
            0x38eae11284842ad78Ad87AaC894c70D180A8DD38
          </RecentSearchComponent>
          <RecentSearchComponent>
            0x38eae11284842ad78Ad87AaC894c70D180A8DD38
          </RecentSearchComponent>
          <RecentSearchComponent>
            0x38eae11284842ad78Ad87AaC894c70D180A8DD38
          </RecentSearchComponent>
          <RecentSearchComponent>
            0x38eae11284842ad78Ad87AaC894c70D180A8DD38
          </RecentSearchComponent>
          <RecentSearchComponent>
            0x38eae11284842ad78Ad87AaC894c70D180A8DD38
          </RecentSearchComponent>
          <RecentSearchComponent>
            0x38eae11284842ad78Ad87AaC894c70D180A8DD38
          </RecentSearchComponent>
        </ContentGrid>
      </RowWrapper>
    </div>
  );
}
